import type { Rune } from "./types";

export const runes: Rune[] = [
  {
    symbol: "ᚠ",
    name: "Fehu",
    meaning: "Wealth, Cattle",
    color: "#FFD700",
    colorName: "Gold",
    reasoning:
      "Gold represents wealth and prosperity, the core meaning of Fehu",
    whisper: "Gold flows to those who seek wisdom...",
  },
  {
    symbol: "ᚢ",
    name: "Uruz",
    meaning: "Wild Ox, Strength",
    color: "#8B4513",
    colorName: "Saddle Brown",
    reasoning: "Earth brown for the wild aurochs and primal strength",
    whisper: "The strength of the wild ox awakens...",
  },
  {
    symbol: "ᚦ",
    name: "Thurisaz",
    meaning: "Giant, Thorn",
    color: "#DC143C",
    colorName: "Crimson",
    reasoning: "Deep red for thorns, blood, and the dangerous power of giants",
    whisper: "Beware the thorns that guard great power...",
  },
  {
    symbol: "ᚨ",
    name: "Ansuz",
    meaning: "God, Divine Breath",
    color: "#4169E1",
    colorName: "Royal Blue",
    reasoning:
      "Sacred blue of the heavens where Odin dwells and divine wisdom flows",
    whisper: "The All-Father whispers divine secrets...",
  },
  {
    symbol: "ᚱ",
    name: "Raidho",
    meaning: "Journey, Ride",
    color: "#32CD32",
    colorName: "Lime Green",
    reasoning: "Green of the path through forests and meadows on long journeys",
    whisper: "Your path leads to destiny unknown...",
  },
  {
    symbol: "ᚲ",
    name: "Kenaz",
    meaning: "Torch, Knowledge",
    color: "#FF4500",
    colorName: "Orange Red",
    reasoning:
      "Bright flame orange of torches that illuminate darkness and bring knowledge",
    whisper: "Knowledge burns brightest in darkness...",
  },
  {
    symbol: "ᚷ",
    name: "Gebo",
    meaning: "Gift, Sacrifice",
    color: "#FF1493",
    colorName: "Deep Pink",
    reasoning:
      "Pink of giving, love, and the emotional bonds created through gifts",
    whisper: "True gifts bind souls across time...",
  },
  {
    symbol: "ᚹ",
    name: "Wunjo",
    meaning: "Joy, Perfection",
    color: "#FFFF00",
    colorName: "Pure Yellow",
    reasoning:
      "Bright yellow of sunshine, happiness, and perfect moments of joy",
    whisper: "Joy is the light that conquers shadow...",
  },
  {
    symbol: "ᚺ",
    name: "Hagalaz",
    meaning: "Hail, Destruction",
    color: "#708090",
    colorName: "Slate Gray",
    reasoning: "Gray of storm clouds and destructive hailstones from the sky",
    whisper: "From destruction, new worlds are born...",
  },
  {
    symbol: "ᚾ",
    name: "Nauthiz",
    meaning: "Need, Necessity",
    color: "#2F4F4F",
    colorName: "Dark Slate Gray",
    reasoning:
      "Dark gray of hardship, survival, and the harsh realities of need",
    whisper: "Necessity forges the strongest steel...",
  },
  {
    symbol: "ᛁ",
    name: "Isa",
    meaning: "Ice, Stagnation",
    color: "#B0E0E6",
    colorName: "Powder Blue",
    reasoning: "Pale blue of frozen water and the stillness of winter ice",
    whisper: "In stillness, the deepest truths emerge...",
  },
  {
    symbol: "ᛃ",
    name: "Jera",
    meaning: "Year, Harvest",
    color: "#DAA520",
    colorName: "Goldenrod",
    reasoning:
      "Golden yellow of ripe grain ready for harvest after a full year",
    whisper: "The harvest rewards patient hearts...",
  },
  {
    symbol: "ᛇ",
    name: "Eihwaz",
    meaning: "Yew Tree, Death",
    color: "#800080",
    colorName: "Purple",
    reasoning:
      "Deep purple of mystery, death, and the sacred yew tree of the dead",
    whisper: "Death is but a doorway to wisdom...",
  },
  {
    symbol: "ᛈ",
    name: "Perthro",
    meaning: "Dice Cup, Fate",
    color: "#4B0082",
    colorName: "Indigo",
    reasoning: "Dark indigo of the unknown, hidden fate within the dice cup",
    whisper: "The dice of fate tumble in mystery...",
  },
  {
    symbol: "ᛉ",
    name: "Algiz",
    meaning: "Elk, Protection",
    color: "#ADFF2F",
    colorName: "Green Yellow",
    reasoning: "Bright green of protective forests where elk find sanctuary",
    whisper: "Protection surrounds those who seek it...",
  },
  {
    symbol: "ᛊ",
    name: "Sowilo",
    meaning: "Sun, Victory",
    color: "#FFA500",
    colorName: "Orange",
    reasoning: "Brilliant orange of the victorious sun at dawn and dusk",
    whisper: "Victory shines upon the worthy...",
  },
  {
    symbol: "ᛏ",
    name: "Tiwaz",
    meaning: "Tyr, Justice",
    color: "#C0C0C0",
    colorName: "Silver",
    reasoning: "Silver of Tyr's blade, justice, and honorable warfare",
    whisper: "Justice cuts both ways, choose wisely...",
  },
  {
    symbol: "ᛒ",
    name: "Berkano",
    meaning: "Birch, Growth",
    color: "#98FB98",
    colorName: "Pale Green",
    reasoning: "Fresh pale green of new birch leaves and spring growth",
    whisper: "New beginnings bloom eternal...",
  },
  {
    symbol: "ᛖ",
    name: "Ehwaz",
    meaning: "Horse, Movement",
    color: "#A0522D",
    colorName: "Sienna",
    reasoning:
      "Rich brown of horse coats and the earth beneath galloping hooves",
    whisper: "Swift movement brings swift change...",
  },
  {
    symbol: "ᛗ",
    name: "Mannaz",
    meaning: "Man, Humanity",
    color: "#CD853F",
    colorName: "Peru",
    reasoning: "Warm tan of human skin, representing all of mankind",
    whisper: "In unity, humanity finds strength...",
  },
  {
    symbol: "ᛚ",
    name: "Laguz",
    meaning: "Lake, Flow",
    color: "#00CED1",
    colorName: "Dark Turquoise",
    reasoning: "Turquoise of deep lake waters and the flow of life",
    whisper: "Life flows like water, ever changing...",
  },
  {
    symbol: "ᛜ",
    name: "Ingwaz",
    meaning: "Ing, Fertility",
    color: "#228B22",
    colorName: "Forest Green",
    reasoning: "Deep green of fertile earth and abundant growing fields",
    whisper: "From small seeds, great forests grow...",
  },
  {
    symbol: "ᛟ",
    name: "Othala",
    meaning: "Heritage, Home",
    color: "#8B0000",
    colorName: "Dark Red",
    reasoning: "Deep red of ancestral blood, family heritage, and hearth fires",
    whisper: "Home is where the heart remembers...",
  },
  {
    symbol: "ᛞ",
    name: "Dagaz",
    meaning: "Day, Awakening",
    color: "#F0E68C",
    colorName: "Khaki",
    reasoning: "Soft khaki of dawn light and the awakening of a new day",
    whisper: "Each dawn brings new possibilities...",
  },
];

export const prophecies = [
  "The seeker of ancient wisdom shall find treasures beyond gold, for those who understand the old ways hold power over fate itself.",
  "Seven runes of power align when wisdom guides the hand. The ancients smile upon your dedication to their sacred knowledge.",
  "You have awakened the constellation of destiny. The threads of fate now weave differently around you, chosen one.",
  "The old gods whisper approval through the mists of time. Your path now leads to mysteries yet undiscovered.",
  "Ancient magic flows through your choices. You have proven worthy of the deepest runic secrets.",
];
